tests/app/test_modifier.py
tests/app/test_retriever.py

Removed errors due to helper functions in test files , and a few minor pep 8 changes , cut short full change as new UI work is a higher priority

Minor code cleanup

---

app/application.py
app/common/utilities.py
app/constants.py
app/resources/drafts.py
app/resources/messages.py
app/settings.py
tests/app/test_draft.py
tests/app/test_retriever.py
tests/app/test_utilities.py
tests/behavioural/features/drafts_get.feature
tests/behavioural/features/steps/drafts_get.py

https://trello.com/c/O9hFY1rW/270-ts-176-(drafts)-as-a-user-i-should-be-able-to-get-a-list-of-drafts-from-a-get-drafts-end-point%7C5%7C
Refactoring:
- moved pagination and options functions to new common utilities file as more than one end point will now be using these functions
- added a new endpoint to get list of drafts
- added bdd test to check all messages returned are drafts and the pagination works
- changed class name Drafts to DraftSave

Ts 176 get list of drafts

---

app/application.py
app/common/utilities.py
app/constants.py
app/repository/database.py
app/repository/retriever.py
app/resources/drafts.py
app/resources/messages.py
app/resources/threads.py
tests/app/test_retriever.py
tests/behavioural/features/steps/threads_get.py
tests/behavioural/features/threads_get.feature

https://trello.com/c/nbZ9ACQY/302-ts-186-conversation-list-view-aka-threads-view-13
- New end point for get threads list
- New function to retrieve threads, with the most recent message, from the database
- Unit tests for the new retriever function
- BDD tests for the new feature
- Additional unit test added for thread by id retriever function (as it wasn't testing descending date_time with drafts)
- Bug with setting date_time for Events found and fixed

Ts 186 return threads endpoint

---

.travis.yml
app/repository/database.py
app/repository/modifier.py
app/resources/drafts.py
tests/app/test_draft.py
tests/behavioural/features/draft_post.feature
tests/behavioural/features/draft_put.feature
tests/behavioural/features/message_get.feature
tests/behavioural/features/message_put.feature
tests/behavioural/features/request_check.feature
tests/behavioural/features/steps/draft_post.py
tests/behavioural/features/steps/draft_put.py
tests/behavioural/features/steps/message_get.py
tests/behavioural/features/steps/message_put.py
tests/behavioural/features/steps/request_check.py

BDD tests implemented

---

tests/app/test_retriever.py
tests/behavioural/features/messages_get.feature
tests/behavioural/features/steps/messages_get.py

Added unit and BDD tests

---

tests/behavioural/features/draft_get.feature
tests/behavioural/features/drafts_get.feature
tests/behavioural/features/message_put.feature
tests/behavioural/features/messages_get.feature
tests/behavioural/features/steps/common.py
tests/behavioural/features/steps/drafts_get.py
tests/behavioural/features/steps/message_put.py
tests/behavioural/features/steps/messages_get.py
tests/behavioural/features/steps/thread_get.py
tests/behavioural/features/steps/threads_get.py
tests/behavioural/features/thread_get.feature
tests/behavioural/features/threads_get.feature

Link to Trello card: https://trello.com/c/Fnxzb3TO 
Added Background to BDD tests.

TS-192 Added background into behave tests 

---

app/repository/database.py
app/repository/modifier.py
app/resources/drafts.py
app/resources/messages.py
app/validation/domain.py
tests/app/test_app.py
tests/app/test_authenticator.py
tests/app/test_draft.py
tests/app/test_message.py
tests/app/test_modifier.py
tests/app/test_retriever.py
tests/app/test_saver.py
tests/app/test_user.py
tests/app/test_utilities.py
tests/behavioural/features/message_get.feature
tests/behavioural/features/message_post.feature
tests/behavioural/features/request_check.feature
tests/behavioural/features/steps/draft_get.py
tests/behavioural/features/steps/draft_post.py
tests/behavioural/features/steps/draft_put.py
tests/behavioural/features/steps/drafts_get.py
tests/behavioural/features/steps/message_get.py
tests/behavioural/features/steps/message_post.py
tests/behavioural/features/steps/message_put.py
tests/behavioural/features/steps/messages_get.py
tests/behavioural/features/steps/thread_get.py
tests/behavioural/features/steps/threads_get.py

https://trello.com/c/WjwsMpAg/328-ts-189-modify-tests-so-that-no-use-of-urn-in-to-and-from-fields-use-uuids-instead3
- Changed any references of urns 
- Modified all unit and BDD tests so they used uuids instead of internal.xxx and respondent.xxx formats

Ts 189 modify tests to use uuids

---

app/repository/database.py
app/resources/messages.py
app/validation/domain.py
tests/app/test_app.py
tests/app/test_draft.py
tests/app/test_logging.py
tests/app/test_message.py
tests/behavioural/features/steps/draft_get.py
tests/behavioural/features/steps/message_get.py
tests/behavioural/features/steps/message_post.py
tests/behavioural/features/steps/message_put.py
tests/behavioural/features/steps/messages_get.py
tests/behavioural/features/steps/thread_get.py
tests/behavioural/features/steps/threads_get.py

https://trello.com/c/bTNLhaar/335-ts-191-validate-that-the-user-in-the-from-field-is-equal-to-the-user-in-the-jwt2
-Added validation to message and draft schema
-modified tests to pass with the validation

Validation added

---

app/repository/modifier.py
app/repository/saver.py
tests/app/test_app.py
tests/app/test_modifier.py
tests/behavioural/features/draft_put.feature
tests/behavioural/features/steps/draft_put.py

https://trello.com/c/uERbxmCC
Added a BDD test to test saving a draft with an apostrophe, Modified the code to use sql alchemy instead of direct queries

D 138 use apostrophes in draft

---

app/common/utilities.py
app/resources/drafts.py
app/settings.py
tests/app/test_app.py
tests/app/test_mock_party.py
tests/behavioural/features/steps/drafts_get.py
tests/behavioural/features/steps/message_get.py

https://trello.com/c/kuYGN0Ap
Modify message output to include @msg_to and @msg_from to contain more details about users.

Ts 203 modify to and from in message

---

app/common/utilities.py

https://trello.com/c/MFoXtMbg/369-modify-use-of-mock-party-service-to-use-list-for-msgto-5
Small change to look for msg_to id's inside a list rather than just the first element. Also will allow multiple msg_to ids to be accepted when other parts of the service become compatible.

all msg_tos are added to list

---

app/authentication/authenticator.py
app/authentication/jwt.py
app/settings.py

Add switch to disable JWT encryption.

---

app/application.py
app/authentication/authenticator.py
app/logger_config.py

Additional logging for tocken decryption and decoding.

---

app/repository/modifier.py
tests/app/test_modifier.py

https://trello.com/c/kFzcqC5Z
Added a test to check for identical labels,
Added an if to check if the label already exists

Modified code so user is Unable to add multiple identical labels

---

app/constants.py

https://trello.com/c/TbD2TIk9
Shortened subject length to 100

shortened subject length to 100

---

app/application.py
app/resources/info.py
tests/behavioural/features/info_get.feature
tests/behavioural/features/steps/info_get.py

https://trello.com/c/3irefzH7
Added new get info end point that currently returns constant JSON. The next stage will be to read this information externally 

Initial push new info end point - values hardcoded

---

tests/app/test_mock_party.py

created generate token function

---

app/validation/domain.py

https://trello.com/c/tV5MOufg
Changed the subject validation check to check for non zero length 

modified subject validation for non zero length

---

app/services/party_service.py

These are changes to handle 404's from other services better. Supporting change in Frontstage PR.

Changes to handle 404 from support services.

---

app/resources/messages.py
app/services/party_service.py

Fixes for content-type.
Stop 500 errors if no party is found.

Release 2 fixes.

---

tests/app/test_logging.py
tests/app/test_service_mock_toggles.py

Test changes

---

app/logger_config.py

Log to include filename and line number.

Add filename and line number to logging.

---

app/logger_config.py

Config for 1 line logging.

---

app/validation/domain.py

Add user uuid to log.

---

app/services/party_service.py
tests/app/test_party_service.py

refacor party servie error handling

---

.travis.yml
app/connector.py
app/repository/retriever.py
app/settings.py
requirements-test.txt
run_tests.py
tests/app/test_app.py
tests/app/test_authenticator.py
tests/app/test_authorizer.py
tests/app/test_case_service.py
tests/app/test_draft.py
tests/app/test_exceptions.py
tests/app/test_health_monitor.py
tests/app/test_labels_count.py
tests/app/test_logging.py
tests/app/test_message.py
tests/app/test_mock_party.py
tests/app/test_modifier.py
tests/app/test_party_service.py
tests/app/test_retriever.py
tests/app/test_saver.py
tests/app/test_service_mock_toggles.py
tests/app/test_user.py
tests/behavioural/features/steps/common.py
tests/behavioural/features/threads_get.feature

Refactor tests not to use sqlite

---

manifest.yml

Adding database service so the binding is created when deploying to cloudfoundry.
https://trello.com/c/2OLpREcU/610-tbl109-p3-ras-ci-pipeline-build-packaging-spike

Add database service

---

README.md

updating default database url

---

secure_message/repository/retriever.py

updating log line to conform with sdc standards

---

config.py

Update JWT_SECRET default value to match other services

updating jwt secret default value

---

secure_message/api_mocks/internal_user_service_mock.py
secure_message/services/internal_user_service.py
secure_message/services/service_toggles.py
tests/app/test_service_mock_toggles.py
tests/behavioural/features/steps/common.py

[card](https://trello.com/c/UPRGrQhE)
Added an internal user service mock and toggle
Ensure service runs and there are no errors

created internal user mock

---

API.md
secure_message/resources/messages.py
tests/behavioural/features/steps/endpoints.py
tests/behavioural/features/v2/messages_get.feature

Update api.md to include V2 endpoints. 
Added more descriptive tests to aid the developer in using the api . 
Also added some some previously stashed passing tests , and fixed a pylint issue.

updated API.md , and added some previously stashed tests

---

API.md
secure_message/application.py
tests/app/test_app.py
tests/app/test_token_functions.py

The API.Md did not have a table of contents

Added contents to api.md

---

config.py

Change default jwt encrypt to disabled to match other services.

Change jwt encrypt to default disabled

---

secure_message/repository/modifier.py
secure_message/repository/retriever.py
secure_message/resources/messages.py
secure_message/v2/validation/domain.py
tests/app/test_app.py
tests/app/test_draft.py
tests/app/test_message.py
tests/app/test_modifier.py
tests/app/test_party_service.py
tests/app/test_retriever.py

Changed a number of "string".format() to f"string" to make it read easier and shorten the length of log lines.
Added additional logging to aid in debugging

Improve logging again

---

Pipfile.lock
secure_message/application.py

Change log levels so that it is more obvious when the app can't reach UAA during startup, but is continuing to try.

Update logging levels to make a startup issue with UAA more visible

---

secure_message/repository/retriever.py
secure_message/resources/threads.py

Added logging for threads in preperation for upcoming work.

Add extra logging, tidy up exceptions

---

config.py

the default sql alchemy pool size was not set , defaulting to None
This defaults to 5 which is the default value in the flask documentation

change config to default to 5 connections

---

secure_message/application.py

This pr addresses an issue where recursive function calls were not returning properly.

fix bug in recursive function calls

---

Pipfile
Pipfile.lock
secure_message/application.py
secure_message/authentication/authenticator.py
secure_message/authentication/jwe.py
secure_message/authentication/jwt.py
tests/behavioural/features/draft_get.feature
tests/behavioural/features/steps/endpoints.py
tests/behavioural/features/threads_get.feature
tests/behavioural/features/v2/threads_get.feature

Removes Pycrypto and python-jose dependencies, which contain security vulnerabilities, in favour of pyjwt.

Remove dependency on python-jose and pycryptodome in favour of pyjwt

---

secure_message/common/utilities.py
secure_message/constants.py
tests/app/test_utilities.py

The get_options was a bit of a mess.  It seemed long and a bit overcomplicated considering what it was doing.  Only 1 place was using the string list of the arguments so that's been culled and done specifically in the one place that it's required.
Moving that allowed the get_options method to become a lot smaller.
Everything should function as before, try to get a message, or a conversation and it should work as expected.

Tidy get options

---

config.py

Release 0.2.0

---

API.md
secure_message/common/labels.py
secure_message/repository/modifier.py
secure_message/repository/retriever.py
secure_message/resources/messages.py
tests/app/test_modifier.py
tests/behavioural/features/message_put.feature

Removed unused archive functionality
[Trello card](https://trello.com/c/3A3QnlxI)
Run tests and check they work
Test different combinations on response-operations and frontstage

Remove unused archive functionality

---

config.py

Prepare release_20180501

---

secure_message/api_mocks/case_service_mock.py
secure_message/resources/messages.py
secure_message/services/case_service.py
secure_message/services/service_toggles.py
tests/app/test_app.py
tests/app/test_case_service.py

Removed a user name from the logs
Test the log does not print out a user name

Remove user name from logs

---

API.md

The API documentation is out of date.  While this PR doesn't completely fix everything, it makes it more accurate.

Add documentation for closing conversations

---

config.py
secure_message/api_mocks/party_service_mock.py
secure_message/common/utilities.py
secure_message/services/party_service.py
secure_message/services/service_toggles.py
secure_message/validation/user.py
tests/app/test_app.py
tests/app/test_mock_party.py
tests/app/test_modifier.py
tests/app/test_party_service.py
tests/app/test_retriever.py
tests/app/test_utilities.py

https://trello.com/c/cJMHZnbR/216-update-secure-message-to-use-new-party-service-batch-call-5
The purpose of this PR is to update secure messaging to use the batch call in the party service repo for the businesses and respondents.
- Run make test and all tests should pass
- Run the acceptance tests to get some messages and you should be able to see all messages on R-ops

Batch respondent and business calls

---

config.py

bumping version to 0.9.1. fyi, it appears this wasn't merged back for the last release

bump version to 0.9.1

---

Pipfile
Pipfile.lock
README.md
config.py
secure_message/application.py

This reverts commit b6df596aaae41f425084faf3aac90a0ab551e307.

Revert "ZipKin Tracing (#227)"

---

secure_message/logger_config.py

Align trace log information with Java services

Align trace naming in logs

---

Makefile
config.py
tests/app/test_alerts.py

Audit environment variables to bring in line with other applications
[Trello] https://trello.com/c/v6e0TLEJ

Bring env vars in line with others

---

secure_message/common/alerts.py
secure_message/exception/exceptions.py
secure_message/resources/messages.py
tests/app/test_alerts.py
tests/app/test_exceptions.py

Improve logging for alerting purposes.
Trello: https://trello.com/c/bdY6GFqq

Improve logging for alerts

---

.travis.yml
secure_message/application.py
secure_message/authentication/authenticator.py
secure_message/common/utilities.py
secure_message/repository/retriever.py
secure_message/resources/messages.py
secure_message/services/party_service.py
secure_message/validation/domain.py

https://trello.com/c/QZQ1NQ73/780-improve-secure-messaging-logging-so-that-reasons-for-failure-to-retrieve-thread-can-be-determined-2
The logging in secure message isn't enough to diagnose all the issues that come from it.  This PR should increase both the amount of logging, and the quality of the logging to make future debugging easier.

Change log level to info for some log lines

---

config.py

Update version to 0.14.0

---

config.py

Bump version to 0.15.0 ready for release to preprod

Update to v0.15.0

---

config.py

increase version

---

config.py

Update version number for release

updates version number to v1.0.1

---

config.py

update version to 1.0.2

---

API.md

This was designed to remove an endpoint, but the endpoint doesn't seem to be anywhere other than the API.MD (so I removed it from there)

Update documentation for non-existant endpoint

---

config.py

update version to 1.1.0

---

config.py

version 1.1.1 

---

_infra/helm/secure-message/templates/deployment.yaml
_infra/helm/secure-message/templates/service.yaml
_infra/helm/secure-message/values.yaml

template the database

---

_infra/helm/secure-message/values.yaml

Update image pull policy to Always
Link to Trello card:
https://trello.com/c/hfeUjOQD

changed pull policy to Always

---

_infra/helm/secure-message/templates/deployment.yaml
_infra/helm/secure-message/values.yaml

add sql proxy

---

_infra/helm/secure-message/templates/deployment.yaml

change secret to look at new cluster-setup secret

---

_infra/helm/secure-message/values.yaml

The service port needed to be changed to 8080.
Changed service port to 8080.
[Trello card](https://trello.com/c/iBBXBpLll)

changed service port

---

_infra/helm/secure-message/Chart.yaml
_infra/helm/secure-message/templates/deployment.yaml
_infra/helm/secure-message/values.yaml

Allowing the selection of different version numbers will allow code changes to be tasted without needing to commit to master.
- Added if-statement in `deployment.yaml` to select version number based on the presence of the `latest` tag in `values.yaml`.
- Updated chart version number.
- Added `latest` tag to `values.yaml`.
[Trello card](https://trello.com/c/Xlj2T6Gi)

made changes to deployment, values, and chart.yaml

---

_infra/helm/secure-message/templates/deployment.yaml

Add quotes

---

.flake8
Makefile
_infra/helm/secure-message/Chart.yaml
secure_message/logger_config.py

Changes to the structlog processor to add severity for the stackdrive

---

_infra/helm/secure-message/Chart.yaml
secure_message/common/utilities.py
secure_message/resources/threads.py
tests/app/test_retriever.py
tests/app/test_utilities.py
tests/behavioural/features/threads_count.feature

A user is now authorized to make a request tot he count endpoint.

remove restriction on count for external user

---

_infra/helm/secure-message/Chart.yaml
_infra/spinnaker/deployment-full.json

syncronize default helm chart

---

.github/workflows/main.yml
_infra/helm/secure-message/Chart.yaml
_infra/spinnaker/prodDeploy.json

Update needed to hash in production pipeline, to use template with release parameters.
Also updated GH Actions to ignore Spinnaker changes in build trigger.
- https://collaborate2.ons.gov.uk/jira/browse/RAS-141

update SHA in prod template, exclude Spinnaker from GH triggers

---

.github/workflows/comment.yml
_infra/helm/secure-message/Chart.yaml

change from sandbox to dev

---

.github/workflows/comment.yml
.github/workflows/main.yml
_infra/helm/secure-message/Chart.yaml

Replace deprecated cmd in GitHub Actions

---

_infra/helm/secure-message/Chart.yaml
_infra/helm/secure-message/templates/deployment.yaml
_infra/helm/secure-message/values.yaml

add proxy resource with minor tweaks to application memory/cpu

---

_infra/helm/secure-message/Chart.yaml
_infra/helm/secure-message/templates/hpa.yaml
_infra/helm/secure-message/values.yaml

add min replicas

---

.github/workflows/comment.yml
_infra/helm/secure-message/Chart.yaml

Use new github action created specifically for ras-rm pr comments.
https://github.com/ONSdigital/ras-rm-spinnaker-action

new comment action

---

.github/workflows/main.yml
Dockerfile
Pipfile
Pipfile.lock
_infra/docker/Dockerfile
_infra/helm/secure-message/Chart.yaml

Upgrade python to 3.9

---

README.md
_infra/helm/secure-message/Chart.yaml

Remove badges

---

_infra/helm/secure-message/Chart.yaml
migrations/004_add_field_category_on_secure_message.sql
secure_message/repository/database.py
tests/app/test_saver.py

secure messages to be routed to the correct teams, so that resourcing can be sufficiently arranged to cover all queries
deploy into environment and validate by viewing the database table
S32 User account creation - Background functionality to route secure messages

add new column with default value and migration script

---

_infra/helm/secure-message/Chart.yaml
migrations/004_add_field_category_on_secure_message.sql

Minor change to allow the migration script to run.
https://trello.com/c/buA9Cnpx/596-s32-user-account-creation-background-functionality-to-route-secure-messages

Correct quotes for migration script

---

_infra/helm/secure-message/Chart.yaml

updating chart version for the codecov changes

Update chart version

---

_infra/helm/secure-message/Chart.yaml
secure_message/common/alerts.py
secure_message/services/party_service.py

Update appversion and add typehints

---

_infra/helm/secure-message/Chart.yaml
_infra/helm/secure-message/templates/deployment.yaml

Update sql proxy from 1.16 to 1.22

---

_infra/helm/secure-message/Chart.yaml
secure_message/repository/retriever.py

https://trello.com/c/sq3yynsR/726-bug-technical-inbox-pagination

Thread count never had category filter, hence adding it

---

Pipfile.lock
_infra/helm/secure-message/Chart.yaml

Upgrade packages

---

Makefile
_infra/helm/secure-message/Chart.yaml
secure_message/repository/saver.py
secure_message/resources/messages.py
secure_message/resources/threads.py
secure_message/validation/domain.py
tests/app/test_message.py
tests/behavioural/features/message_post.feature
tests/behavioural/features/steps/message_category_field.py
tests/behavioural/features/steps/survey_field.py
tests/behavioural/features/steps/thread_state.py

https://trello.com/c/XQ2gnUbP/369-s37-user-account-creation-something-else

User account creation something else

---

_infra/helm/secure-message/Chart.yaml
secure_message/repository/modifier.py

Where was a bug around changing category, but it wasn't clear what was going on.  This PR adds more logging to the repo to give more information for debugging purposes.

Add additional logging

---

.github/workflows/main.yml
_infra/helm/secure-message/Chart.yaml

Update chart versions automatically

---

_infra/helm/secure-message/Chart.yaml
secure_message/api_mocks/party_service_mock.py
secure_message/resources/messages.py
secure_message/services/party_service.py
secure_message/services/service_toggles.py
tests/app/test_mock_party.py
tests/behavioural/features/message_post.feature

https://trello.com/c/63Y9ZRBh/855-weaken-secure-message-claim-functionality

weakening claim functionality to only check business associations only

---

Pipfile.lock
_infra/helm/secure-message/Chart.yaml
_infra/helm/secure-message/values.yaml

Dev was running a bit slow, especially the smoke tests.  Upping the resources in secure message appears to fix the issue.

Increase resources in dev

---

.github/workflows/main.yml
Dockerfile
Pipfile
Pipfile.lock
_infra/docker/Dockerfile
_infra/helm/secure-message/Chart.yaml

Python version needed to be updated 3.10.
TBD
[Card](https://trello.com/c/9UoxbBgP)

upgraded python to version 3.10

---

_infra/helm/secure-message/Chart.yaml
_infra/helm/secure-message/templates/deployment.yaml

Fix the deployment of secrets

---

Pipfile.lock
_infra/helm/secure-message/Chart.yaml
_infra/helm/secure-message/templates/deployment.yaml
_infra/helm/secure-message/values.yaml

Upgrade cloudsql proxy

---

.github/workflows/main.yml
Makefile
_infra/helm/secure-message/Chart.yaml

Removal of deprecated github action
https://trello.com/c/JyPxSmDA/2298-replace-soon-to-be-deprecated-set-output-in-github-actions

Fix setoutput

---

_infra/helm/secure-message/Chart.yaml
secure_message/validation/domain.py

Adjust logging

---

_infra/helm/secure-message/Chart.yaml
secure_message/scripts/find_old_message_threads.sql

We want the ability to find any threads with no new messages in over a year.
RAS-355

Create an SQL script for finding and deleting old messages/threads

---

Pipfile.lock
_infra/helm/secure-message/Chart.yaml

Flask upgrade
Deploy and run acceptance tests.
[card](https://jira.ons.gov.uk/browse/RAS-784)

flask upgrade

---

_infra/helm/secure-message/Chart.yaml
secure_message/resources/messages.py

This will stop SM calling out to party unnecessarily 
Generate a message thread and make sure it still works

RAS-1265 Correct order of claim call in secure messaging
