ONSdigital/ras-secure-message

- app/application.py
- app/repository/retriever.py
- app/resources/drafts.py
- app/resources/threads.py
- tests/app/test_retriever.py
- tests/behavioural/features/steps/thread_get.py
- tests/behavioural/features/thread_get.feature
https://trello.com/c/MESJU17r/277-ts-184-as-a-user-i-want-to-be-able-to-retrieve-a-conversational-thread-of-messages-by-thread-id%7C8%7C
-Added a new endpoint 'ThreadById'
-Added new retriever function for thread id
-Unit tests for Retrieve_thread function 
-BDD test for the new feature
> Get conversation by thread id endpoint and tests added

- tests/behavioural/features/steps/draft_get.py
- tests/behavioural/features/steps/draft_post.py
- tests/behavioural/features/steps/draft_put.py
- tests/behavioural/features/steps/drafts_get.py
- tests/behavioural/features/steps/message_get.py
- tests/behavioural/features/steps/message_post.py
- tests/behavioural/features/steps/message_put.py
- tests/behavioural/features/steps/messages_get.py
- tests/behavioural/features/steps/request_check.py
- tests/behavioural/features/steps/thread_get.py
Codecy is giving errors because it cannot differentiate between multiple implementations of functions with the same name . Behave is ok because it uses the decorators . If we do not do this we are starting to ignore codecy issues so we are more likely to miss more important issues if we do not do this 
Link to Trello card : https://trello.com/c/F29ek6LZ
Changed the step_impl function names so that the name is close to the decorator string and hence does not clash 
> Ts 185 change function names for codecy checks

- app/repository/database.py
We have not defined any indexes apart from the primary index on all the tables . Therefore each query will result in table scans and would hence be slow , but only as the number of messages scales. This ticket is a first pass attempt to create the more obvious indexes on the tables . We should follow this up during the non functional testing to be sure that no table scans take place by using the Postgres tools .
https://trello.com/c/RgYPkRj5
For single column indexes , simply add index=True to the column definitions . Multi column indexes are a little more obtuse to define , and its done by adding a tuple to the __table_args__ variable in the model . …
> Ts 179 add initial indexes

- app/validation/domain.py
- tests/app/test_message.py
- tests/behavioural/features/steps/message_post.py
https://trello.com/c/HIOinMzX/305-ts-187-as-a-user-of-thesecure-message-api-an-exception-should-be-thrown-if-i-submit-a-message-post-where-the-to-and-from-fields
-  Added validation to check to and from fields are not equal
-  Unit test added
-  Fixed BDD test to work with new validation
-  Made 'subject' a required field and changed tests accordingly 
> Added validation for to and from fields and made subject field required

- app/authentication/authenticator.py
- app/common/utilities.py
- app/repository/database.py
- app/repository/modifier.py
- app/repository/retriever.py
- app/resources/drafts.py
- app/resources/messages.py
- app/resources/threads.py
- app/validation/user.py
- tests/app/test_app.py
- tests/app/test_authenticator.py
- tests/app/test_draft.py
- tests/app/test_modifier.py
- tests/app/test_retriever.py
- tests/app/test_user.py
- tests/app/test_utilities.py
- tests/behavioural/features/messages_get.feature
- tests/behavioural/features/request_check.feature
- tests/behavioural/features/steps/draft_get.py
- tests/behavioural/features/steps/draft_post.py
- tests/behavioural/features/steps/draft_put.py
- tests/behavioural/features/steps/drafts_get.py
- tests/behavioural/features/steps/message_get.py
- tests/behavioural/features/steps/message_post.py
- tests/behavioural/features/steps/message_put.py
- tests/behavioural/features/steps/messages_get.py
- tests/behavioural/features/steps/request_check.py
- tests/behavioural/features/steps/thread_get.py
- tests/behavioural/features/steps/threads_get.py
- Added user uuid and role claims into JWT 
- Changes made to "User" class to work with the user_uuid and role
- When authorising the request a global user object is created, which is then passed into various functions instead of passing the global user_urn.
- Unit tests and BDD tests modified to work with UUIDs instead of user_urns
https://trello.com/c/EW2mmOJ5/312-ts-188-every-sm-api-call-to-require-a-jwt-which-will-include-a-user-uuid-and-a-claim-as-to-if-the-current-user-is-an-internal-us
> Changes from user_urn to UUIDs and roles added

- app/resources/drafts.py
- app/resources/messages.py
- tests/behavioural/features/message_post.feature
- tests/behavioural/features/steps/message_post.py
https://trello.com/c/GsjsyZgy/338-d-136-message-post-of-draft-issue-with-threads
- In the message send endpoint there is now a check for if the thread id is the same as the msg id when posting a draft if it is then this thread id is not persisted.
- BDD tests added to cover this bug 
- Refactored draft save endpoint as there was a function which added no value
> Bug fixed and bdd tests added

- app/common/utilities.py
- tests/app/test_mock_party.py
API was returning 417 if it could not populate business details or user details for messages found in the database.
This change allows the API to return the messages even if no matching data in party service.
> Log if business details or user details not found in party service.

- app/validation/domain.py
- tests/app/test_message.py
https://trello.com/c/OCyBb8FX/527-sm070-external-validate-secure-message-before-sending-m-5
Changed returned error messages for secure messaging validation
Use with associated frontstage PR 
https://github.com/ONSdigital/ras-frontstage/pull/159
> upadting returned error messages for saved message

- app/services/case_service.py
- app/services/party_service.py
- app/settings.py
https://trello.com/c/ZAvBcNgf/562-defect-23-production-pre-prod-services-communicating-with-eachother
Basic auth settings have been added for SECURITY_USER_NAME and SECURITY_USER_PASSWORD. Note that these match the names of the environment variables across RAS and RM, as the username/password is to be shared across services (while being distinct per environment). These parameters are passed into downstream calls to party service and case service.
> Pass basic auth parameters to downstream services

- app/authorization/authorizer.py
- tests/app/test_authorizer.py
- tests/behavioural/features/draft_get.feature
- tests/behavioural/features/draft_post.feature
https://trello.com/c/nvudG3Bb/567-bug-if-a-user-saves-a-draft-the-intended-recipient-can-read-it-if-they-request-drafts-with-a-draftinbox-label
Added check to make sure the user cannot view message if he is the `msg_to` and the message is labelled `DRAFT_INBOX`
Try to view a message with the `DRAFT_INBOX` label where the user is the `msg_to`
> user can no longer view messages from DRAFT_INBOX

- app/common/alerts.py
https://trello.com/c/inAx7xet/652-defect-57-found-in-r9-fixed-in-release-notify-a-respondent-when-a-secure-message-has-been-sent-to-them-this-is-not-working-no-em
> Add logging

- app/common/utilities.py
- app/repository/database.py
Limited the body size on messages returned in a list to 100 chars.
Also changed data loading in sqlalchemy from the default 'select' to 'dynamic'.
> Limit body size for list of messages

- app/validation/domain.py
- tests/app/test_message.py
Subject was passing validation if it only contained spaces. Now it will raise a validation error if the message being sent has a subject just filled with spaces.
Trello: https://trello.com/c/ICXHAdV6/676-secure-messages-sent-with-only-spaces-in-subject-cannot-be-viewed-in-rops
> Subject with only spaces can not be sent

- secure_message/resources/health.py
- tests/app/test_health_monitor.py
The healthcheck endpoint was exposing the db url, this has now been removed.
> Remove db url from healthcheck

- Dockerfile
- docker-compose.yml
The f-string notation didn't come until python 3.6 which is why the image was updated.
The dockerfile didn't have any environment variables set so now it'll work out of the
box in accordance with the readme.
> Fix dockerfile

- config.py
- tests/behavioural/features/steps/info_get.py
Fixes an issue where an increment to the version number fails unit tests. The fix uses Flask's testing_app config to get the actual version number, instead of having it hard coded in the tests.
> Fixes an issue where tests fail after incrementing a version

- config.py
- run_tests.py
- secure_message/application.py
- secure_message/authentication/jwt.py
- tests/app/test_authenticator.py
- tests/behavioural/features/steps/common.py
Fixes #130. Removes a for loop at the bottom of the config file that checked whether non default vars were set. This would always fail when running dev or test, as these environments expect the `TestConfig` and `DevConfig` config classes to be used.
This PR also removes workarounds put in place to mitigate this bug.
> Fix startup config errors

- secure_message/logger_config.py
- tests/app/test_logging.py
Set logger to use stdout for streaming in logger config. This will stop cloudfoundry logging all application logs at stderr.
https://trello.com/c/RW1t6CDZ
Added stream as a parameter for logging basic config in the logger config and passed stdout to stop the default stderr being used.
Currently deployed in test environment so hitting any the endpoint should show the logs no longer being stderr.
> Update logger to use stdout streaming

- Makefile
- README.md
> Add simple makefile and update readme

- Pipfile
- Pipfile.lock
- secure_message/application.py
Adding retry mechanism for when service is up before database. It means that the service will try every 2 seconds for 30 seconds to connect
Run service without database, start database after a few seconds and it should connect
> Database resilience

- secure_message/authentication/authenticator.py
- secure_message/authentication/jwe.py
Previously an exception would be raised, but nothing would be logged and you would have to
look at logs of other applications to get a hint of what went wrong.  Now we catch the exception
log an error with the same error text, then raise the exception again.
This way the functionality doesn't change, and we get better logging!
> Improve logging

- secure_message/services/internal_user_service.py
- tests/app/test_internal_user_service.py
- tests/behavioural/features/steps/to_field.py
The ras-rm-docker-dev setup has a bootstrapped user. This user 'uaa_user' does not have a given or family name so therefore secure messaging fails with a key error.
In this scenario return a default user of ONS
> Default user details if they're not in the UAA

- secure_message/application.py
- tests/behavioural/features/draft_get.feature
- tests/behavioural/features/steps/endpoints.py
- tests/behavioural/features/threads_get.feature
- tests/behavioural/features/v2/threads_get.feature
SM111 is showing the threads , this means it displays the last message in a conversation which may be a draft. There were no tests to prove there would be no issues in the API if there was no 'to' specified.
> Added tests for retrieving a thread or draft when the returned message is a draft and with no 'to' field set. 

- .travis.yml
- Makefile
- secure_message/application.py
This pull request enables linting on Travis. This has been done via the make targets so there is consistency between running the commands locally and on Travis.
The pipenv --style option has been deprecated (https://github.com/pypa/pipenv/blob/master/HISTORY.txt#L66) so this pull request also uses flake8 explicitly.
- Run make lint locally, it should run successfully
- Verify Travis runs the linting
**Note**: Travis will fail until #169 merges as the `pipenv check` command is now being run properly and finds security vulnerabilities.
> Make linting part of testing and enable on Travis

- secure_message/repository/modifier.py
- secure_message/resources/messages.py
- tests/app/test_modifier.py
**Fix for bug in modify labels endpoint**
The endpoint to modify labels on a message still had a hardcoded BRES constant, it could not cope with messages from or to specific internal users or the GROUP constant.
I have added logic to choose the appropriate actor so that the endpoint works.
**How to review:**
Currently these fixes are only needed for features on this branch of response-operations-ui:
[sm114/distinguish-unread-messages](https://github.com/ONSdigital/response-operations-ui/tree/sm114/distinguish-unread-messages)
**To replicate the bug:**
Run that response-operations branch and open an unread message from a respondent. The call to mark messages as read will not work, when you got back to the inbox it will still be highlighted unread as the call to update the label fails.
If …
> Fix label updating to handle GROUP and internal users

- README.md
- tests/behavioural/features/environment.py
- tests/behavioural/features/steps/common.py
- tests/behavioural/features/steps/endpoints.py
- tests/behavioural/features/steps/info_get.py
The behave tests were creating the Flask test client on every interaction with an endpoint, which meant the tests took far longer than necessary. This pull request creates the test client before all tests in `before_all` leading to a ~4x speedup of the tests.
This pull request also sets the config to `TestConfig` when creating the app. This allows use of the behave command to run all tests - `pipenv run behave` - or run an individual feature - `pipenv run behave tests/behavioural/features/v2/thread_get.feature` 
- Run all tests with `pipenv run behave`
- Run an individual feature with `pipenv run behave tests/behavioural/features/v2/thread_get.feature`
> Speed up tests by only creating the Flask test client once

- secure_message/common/utilities.py
- secure_message/resources/drafts.py
- secure_message/resources/messages.py
- secure_message/resources/threads.py
paginated_list_to_json did too much and didn't describe what it was doing well enough (it does a lot more than taking a list and turning it into json).
Splitting this out will make the code slightly more readable, as it's a bit more obvious at a glance what is going on instead of it being hidden away by a function.  Also, it'll aid in the removal of the pagination in threads which we're going to do shortly.
Open a conversation and the messages should appear as expected
> Split out utility method functionality and renamed it

- secure_message/common/utilities.py
- secure_message/repository/retriever.py
- secure_message/resources/threads.py
- tests/app/test_retriever.py
- tests/app/test_utilities.py
- tests/behavioural/features/steps/endpoints.py
- tests/behavioural/features/steps/secure_messaging_context_helper.py
- tests/behavioural/features/v2/threads_get.feature
**Fix a bug that was preventing multiple surveys in the filter**
Secure message was not properly handling filtering by multiple surveys
The condition for the filter in the database query was checking for equality so would not work as expected for lists of multiple surveys, now it checks for inclusion, and lists of surveys in the parameters are handled.
Dependent on this branch of ras-backstage:
[Ras Backstage: Fix multiple surveys secure message](https://github.com/ONSdigital/ras-backstage/pull/90)
Requires this branch of ras-backstage:
[Ras Backstage: Fix multiple surveys secure message](https://github.com/ONSdigital/ras-backstage/pull/90)
When running both this branch and the backstage fix branch, you should be able to filter by multiple survey ids in the parameters. …
> Fix filtering by multiple survey

- tests/app/test_retriever.py
There is a card to remove all instances of drop_all as unit tests shouldn't be deleting database data.  Doing this will require a lot of work as instead of dropping the data and then hitting endpoints to add/remove data, you'd have to mock the responses.
This is a small first pass at that work by removing the tests that deleted the table and then tested that it was broken.  Those tests don't provide value as that situation would never arise.  And if it did, the cause would be obvious.
> Remove tests that drop tables to see if it breaks.

- Makefile
- Pipfile.lock
The hash of pluggy 0.6.0 has been incorrectly updated, but this is causing a build failure with a fresh virtual environment. This PR updates the hash to match the remote ones. So the pluggy defect below for more details
https://github.com/pytest-dev/pluggy/issues/135
> Updating pluggy 0.6.0 hashes

- migrations/001_create_event_dates_on_message.sql
Adds `sent_at` and `read_at` columns to the `secure_message` table in preparation for the code change that will populate these columns.
- Run the migration SQL against the secure message database, if running the ras-rm-docker-dev setup you can use `psql -h localhost -p 6432 -U postgres -d postgres -a -f migrations/001_create_event_dates_on_message.sql`
- Use the service and verify it works
- Run the acceptance tests
> Add migration for event date columns on message table

- secure_message/application.py
- secure_message/repository/retriever.py
- secure_message/resources/messages.py
- secure_message/resources/threads.py
- tests/app/test_retriever.py
https://trello.com/c/q17Lr227/208-fix-pagination-in-secure-messaging
A bug existed in secure message where not all pagination links were showing.  When retrieving the counts of messages by survey, the SQL was retrieving a count of any conversations logged against the current user (their uuid) or GROUP.  If  different user logged in then the count wasn't retrieving all conversations.  
&nbsp;  
&nbsp;  
To recreate the issue:
- Bring everything up in Docker
- Run the acceptance tests to set up conversations
- Log in as uaa_user and create a few more conversations to push the pagination to the 5th page
- Log in as a different internal user (see below for instructions)
- Navigate to messages - only the first 2 pages are displayed, …
> Fix pagination bug

- secure_message/resources/health.py
- secure_message/resources/messages.py
- secure_message/resources/threads.py
- tests/app/test_health_monitor.py
- tests/app/test_modifier.py
- tests/app/test_retriever.py
Previously, a lot of calls were in the form of <class>().<function> (i.e., Retriever().get_something())
The brackets are unnecessary as that creates the object of that module, then calls the function on it which
needlessly taking extra memory.
> Cleaned up a number of function calls

- add-convo-record-for-every-convo.py
This is the next step in the db migration and is needed to put the data to a consistent state and to allow for the following PR's to be mergeable:
https://github.com/ONSdigital/ras-secure-message/pull/212
https://github.com/ONSdigital/ras-frontstage/pull/352
Trello card: https://trello.com/c/wC4PUlNr/12-add-conversation-record-for-every-conversation-3
Does it work? 
- Try removing an` id` from your `conversation` table and its corresponding key from the `secure_message `table 
- Check that when you run the script 
i.e. `python add-convo-record-for-every-convo.py` that it is added. 
- You can do a print statement to check the actual SQL that is ran and check what gets inserted into the `conversation` table.
> Add conversation record for every conversation

- secure_message/validation/user.py
The validator in secure messaging is currently sending to the wrong function, it should be get_user_details, instead it is calling to get_users_details which then separates the uuid into its parts and throws an exception. This PR is only to stop the noise the exception is causing and fix the immediate issue as it is in prod, the fact that the exception wasn't being handled and saying the message was valid when it was not will be raised in another card. 
Send a message internally and check the logs aren't throwing a exception
> Fix incorrect call to get user details

- secure_message/authentication/jwt.py
- secure_message/resources/messages.py
- tests/app/test_app.py
- tests/app/test_saver.py
- tests/integration/test_case_service_integration.py
Case events weren't being generated by secure message as key errors were being hit fromuser_data
send a message from frontstage to rops, search for `AttributeError` in logs, should not see one
> Index list to enable case events being generated by secure message

- Pipfile
- Pipfile.lock
- README.md
- config.py
- secure_message/application.py
Motivation and Context
==
Currently there's no way to trace the requests through the application.
What Changed
==
This will add the tracing headers to any request that comes through this
application onto another service, or preserve existing headers allowing
the user to follow requests through the application as a whole.
There are also new configuration settings:
```
| ZIPKIN_DISABLE                  | Totally disable Zipkin (including tracing headers)            | False
| ZIPKIN_DSN                      | Zipkin Sample API URL (e.g. http://zipkin:9411/api/v1/spans)  | None
| ZIPKIN_SAMPLE_RATE              | Percentage of requests to send to zipkin span API             | 0
```
By default this will add the tracing headers, but make no requests to
Zipkin's neat little UI.
How to test
==
No …
> ZipKin Tracing

- Pipfile
- Pipfile.lock
- README.md
- config.py
- secure_message/application.py
Motivation and Context
==
Currently there's no way to trace the requests through the application.
What Changed
==
This will add the tracing headers to any request that comes through this
application onto another service, or preserve existing headers allowing
the user to follow requests through the application as a whole.
There are also new configuration settings:
```
| ZIPKIN_DISABLE                  | Totally disable Zipkin (including tracing headers)            | False
| ZIPKIN_DSN                      | Zipkin Sample API URL (e.g. http://zipkin:9411/api/v1/spans)  | None
| ZIPKIN_SAMPLE_RATE              | Percentage of requests to send to zipkin span API             | 0
```
By default this will add the tracing headers, but make no requests to
Zipkin's neat little UI.
How to test
==
No …
> Zipkin flask

- secure_message/exception/exceptions.py
- tests/app/test_exceptions.py
Logging out data for a ras-notify error comes out in a wrong format by only printing out the values. This PR turns the description of the error into a key/value pair instead of only the value.
- Stop notifygateway and send a message from internal to external. Secure Message should log out RasNotifyException in a key/value pair
- Run acceptance tests and unit tests
> Changed log line to key value pair for RasNotifyException

- Dockerfile
- Pipfile.lock
- secure_message/validation/domain.py
Python Docker Images are ~1GB.  This is because of the base image.
Starting using python:3.6-slim instead
System should behave as before, acceptance tests should workfinr
https://trello.com/c/x0swxIs4/358-tbl358-review-base-docker-images
> Change Dockerfile to use smaller base image

- API.md
For this PR I have been looking at the redundant API endpoints for secure message.
[Trello Card](https://trello.com/c/ODTURAH3)
Added a note to the API.md file to identify the "/labels" endpoint as unused in the code.
Check API.md is correct.
> marked redundant /labels endpoint in documentation

- API.md
- secure_message/api_mocks/party_service_mock.py
- secure_message/resources/messages.py
- secure_message/services/party_service.py
- secure_message/services/service_toggles.py
- tests/app/test_app.py
- tests/app/test_mock_party.py
- tests/behavioural/features/message_post.feature
- tests/behavioural/features/steps/endpoints.py
- tests/behavioural/features/steps/secure_messaging_context_helper.py
- tests/behavioural/features/steps/user.py
- tests/behavioural/features/v2/threads_count.feature
- tests/behavioural/features/v2/threads_get.feature
There was no validation that a user had a claim on a survey/ru. Which meant that if a valid user had a url they could send a message in a conversation that they should not be able to. This change validates the claim prior to being able to post a message .
This change is the second attempt. The first used claims passed in the JWT, however it was discovered that this failed at a level of survey/ru combinations that was not significantly higher than that in production, and although it was a cleaner design it could be an insidious bug. Therefore it was decided to add an end point to party and have secure message validate the claim prior to message post. Other endpoints did not need such protection, get for example uses the user id as …
> Validates user claim on message post by calling out to party

- config.py
- secure_message/repository/retriever.py
- tests/app/test_retriever.py
- tests/behavioural/features/v2/threads_get.feature
Made change to frontstage to show 403 error when accessing message that does not belong to the user. Had to make the change to return a 403 rather than a 404 in secure message.
https://trello.com/c/iWD6OxY9/824-403-message-thread-not-found-status-page-3
runtests in secure message
> 403 forbidden access to secure message

- Pipfile.lock
- config.py
- secure_message/application.py
- secure_message/common/alerts.py
- secure_message/resources/messages.py
- secure_message/resources/threads.py
- tests/app/test_message.py
secure-message had a few packages that had security issues.
In fixing them, a few other issues were revealed that I also fixed. These were
- A test failed because of a keyError on a dictionary.  It's not clear how the test ever passed, but now it uses the .get() functionality of a dictionary to not break.
- SQLALCHEMY_POOL_SIZE is deprecated and will be removed in 3.X.  We don't configure it anywhere, and we set it to the default (5) when we don't provide a value for it.  Might as well not have it.
- Updates to flake8 and pylint revealed 2 new errors.  These were easy to fix.
- Unit and acceptance tests should still pass.
> Fix security issues

- secure_message/repository/retriever.py
- secure_message/resources/messages.py
- secure_message/resources/threads.py
- secure_message/validation/domain.py
https://trello.com/c/XMxhigG8
We were getting alerts because of the number of errors that were being thrown.  A lot of the errors in secure message can be put to info level as we should only have things at the error level that are actionable (databases failing, tokens not decoding, missing config items, etc).  Things that aren't actionable (api being called with wrong parameters, trying to close closed conversations, etc) don't need to be errors as the user will have the appropriate error screen presented to them as this api returns sensible http status codes in the response.
- Unit tests still pass.
- Check all the changed files to make sure nothing was mistakenly changed
- Check all the remaining logger.error lines to make sure that …
> Change a lot of logging from error to info

- secure_message/repository/retriever.py
In prod on the new initial tab only, the number of records returned is limited to 5 per page instead of 10 . The reason for this is that the query that was produced by SqlAlchemy was counting INBOX and UNREAD labels and since one message has both it returned half the expected records.
By specifying the INBOX label it specifically avoids this and returns the correct amount.
To test:- create > 10 new messages from respondent and validate that there are 10 shown on the first page and that the pagination count is correct
> Added extra clause in initial so as to not count UNREAD label 

- secure_message/resources/messages.py
- tests/behavioural/features/message_post.feature
- tests/behavioural/features/steps/secure_messaging_context_helper.py
- tests/behavioural/features/steps/to_field.py
It's not possible to reply to deleted users.  A similar change has been made in response-operations-ui, but we need to do a check here incase the client gets around this restriction.  
https://trello.com/c/3TkwE4E8
Follow the 'test additional logic' part of the guide in https://github.com/ONSdigital/response-operations-ui/pull/371 Testing that will test this as secure-message is the part that generates the 404
> Cannot reply to deleted message

- API.md
- secure_message/common/utilities.py
- secure_message/repository/retriever.py
- secure_message/resources/threads.py
- tests/app/test_retriever.py
- tests/app/test_utilities.py
- tests/behavioural/features/steps/common.py
- tests/behavioural/features/steps/endpoints.py
- tests/behavioural/features/steps/secure_messaging_context_helper.py
- tests/behavioural/features/steps/status_code.py
- tests/behavioural/features/steps/thread_state.py
- tests/behavioural/features/thread_patch.feature
- tests/behavioural/features/threads_count.feature
https://trello.com/c/3Bj1gYTy
There is a need to display the counts of secure message conversations in the title of each tab .
This PR enables that through a call to Secure message. 
It adds support for all_conversation_type parameter in the Thread count end point. This returns counts for open,closed,new_respondent_conversations and my conversations all in one endpoint. Its not practical to fulifil this in a single database query, a single conversation can count in multiple classes, and the selection criteria are complex. This code submits 4 queries and amalgamates the data .  
Run tests. New tests added for the additional parameter.
> Return multiple counts

- _infra/helm/secure-message/templates/deployment.yaml
- _infra/helm/secure-message/values.yaml
The helm charts needed to have the option of selecting different repos when a developer is testing changes.
- The `deployment.yaml` now switches to the devRepo if the `latest` tag is not set.
- Added the devRepo to `values.yaml`. As of now, it is the same as the current image's repo, but will be different in prod and pre-prod.
[Trello card](https://trello.com/c/fLbRN0qG)
> added devRepo

- API.md
- _infra/helm/secure-message/Chart.yaml
- migrations/003_increase_message_field_length_to_50000.sql
- secure_message/constants.py
- tests/behavioural/features/thread_get.feature
The message body character limit needed to be increased to 50,000.
**Changes**
- Changed character limit to 50000 and adjusted documentation accordingly.
Create a message of more than 10000 characters and ensure that the system allows it.
**Links**
[Jira card](https://collaborate2.ons.gov.uk/jira/browse/RAS-16)
> changed message body character limit to 50000

- README.md
- _infra/helm/secure-message/Chart.yaml
Just a small addition to the readme about database migrations. I was looking around this service to see if we use any tools for database migration, but we don't, it seems. I originally thought this service might have used Flyway, but that's only usable with Java, not Python. I discussed this with Adam Mann and he said that previously, database migrations had always been executed manually on the database because that was easier than using tools.
**Changes**
- Updated `README.md`
> updated readme about database migrations

- Makefile
- _infra/helm/secure-message/Chart.yaml
- secure_message/repository/modifier.py
- tests/app/test_alerts.py
- tests/app/test_modifier.py
If an internal users sends two messages to an external respondent then it was impossible to mark the first as read so the user would always have a notification for it.
This change marks all messages in the thread as read when the latest one is.
https://trello.com/c/4PRWzCg3/234-ritm0459542-respondent-has-notification-of-unread-message-but-when-they-look-in-open-and-closed-there-are-no-new-messages
> Mark all messages in a conversation as read

- .github/workflows/main.yml
- _infra/helm/secure-message/Chart.yaml
During the release step tag the generated docker image as both the release version and latest.
> Docker tag latest at the same time as the release

- _infra/helm/secure-message/Chart.yaml
- secure_message/resources/threads.py
There was an assumption made that the most recent message in thread would have an 'INBOX' label against it.  This is isn't always in the case (I think, in the case where an internal person has sent a message to a respondent, and then you get the threads messages as an internal user?).
This PR only marks a message as unread in response ops if the last message was from a respondent, and it has the inbox label.  We don't need to mark our own messages as unread as that's pointless.
> Only mark unread in certain scenarios

- Makefile
- _infra/helm/secure-message/Chart.yaml
- migrations/006_remove_events_table.sql
- secure_message/common/eventsapi.py
- secure_message/constants.py
- secure_message/repository/database.py
- secure_message/repository/modifier.py
- secure_message/repository/retriever.py
- secure_message/repository/saver.py
- secure_message/resources/messages.py
- tests/app/test_app.py
- tests/app/test_modifier.py
- tests/app/test_retriever.py
- tests/app/test_saver.py
The event table hasn't been needed for a while.  The info it stores is also stored against each message (as `sent_at` and `read_at`).  This PR removes all mention of it and updates the few places it was used to use the new columns.  This should simplify the design of this service greatly.
- Run acceptance tests in dev environment
- Create 2 more threads (internal to external, and the reverse)
- Deploy app to your environment
- Test it manually (check threads on both internal and external look as expected)
- After testing to make sure it works, delete the events table (with supplied script in PR).  Make sure it still works (manually and/or with acceptance tests)
Through my testing I saw that it worked just fine regardless of what state the database was in as long as the schema (and …
> Remove events table

- Pipfile.lock
- _infra/helm/secure-message/Chart.yaml
- _infra/helm/secure-message/templates/deployment.yaml
We have 2 secrets which are both for Secure Message to talk to UAA. Only one of those is needed
https://trello.com/c/rROZ6a0w/1372-make-the-uaa-client-credentials-more-secure
> Change which secret connects to UAA

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/secure-message/Chart.yaml
This PR updates Github actions to fix "service_account_key" has been deprecate. Replacing it with google-github-actions/auth in both main.yml and comment.yml
For main.yml check https://github.com/ONSdigital/ras-secure-message/runs/7247991625?check_suite_focus=true
For comment.yml see https://github.com/ONSdigital/response-operations-ui/pull/747 on how I tested in response-operations, as it is a virtual copy bar the service I didn't repeat it here
> Fix secure account key deprecation

- _infra/helm/secure-message/Chart.yaml
- secure_message/services/internal_user_service.py
If an internal user has been deleted, any thread that comes from that user will generic 500 as the 404 from UAA isn't handled properly. This fixes it by just returning the default "ONS User" text that we already return if we end up with only partial information from UAA.
- Make a thread between an internal and external user
- Delete the internal user
- Check your message thread as an internal user; it shouldn't throw a 500 and should appear as being from "ONS User"
https://trello.com/c/GOu2O5zI/1937-bug-handle-missing-internal-users-properly-in-secure-message-15m
> Return default user details when internal users not found

- Pipfile
- Pipfile.lock
- _infra/helm/secure-message/Chart.yaml
- tests/behavioural/features/steps/secure_messaging_context_helper.py
There was a vulnerability in our packages.  This PR bumps everything possible to the latest version to fix it.  One thing that we couldn't bump past a certain version was Flask.  When it's set to =>2.2.x then the behave tests fail.  We can address this in another card specifically.
- Deploy app
- Run acceptance tests
- Use the secure message functionality yourself a bit.  It should all work
> Fix vulnerable packages

- .github/workflows/main.yml
- _infra/helm/secure-message/Chart.yaml
Currently on a push to a PR each repo builds to latest in onsrasrm-management, however this is the default artifact for all builds when using spinnaker. This means if any change to the charts are made and a PR is created it can and will break dev for everyone. 
Check the build (Publish dev Chart) and make sure it is writing naming the artifact correctly, it should be xx-pr-xx.tgz. You can also check on GCP in ons-rasrmbs-management that the artifact was written out at the right time
> Update publish chart dev

- Makefile
- Pipfile.lock
- _infra/helm/secure-message/Chart.yaml
Currently we have 2 pipenv checks that are failing the build, one concerns py and the other one is a temporary fix which ignores 51499: wheel
Test everything still works
> Remove pipenv check ignore

- Makefile
- Pipfile
- Pipfile.lock
- _infra/helm/secure-message/Chart.yaml
- secure_message/repository/modifier.py
- secure_message/repository/retriever.py
- tests/app/test_app.py
- tests/app/test_health_monitor.py
- tests/app/test_modifier.py
- tests/app/test_retriever.py
- tests/app/test_saver.py
- tests/behavioural/features/steps/common.py
Flask version used to be pinned; this PR unpins in and sorts out various test failures that result from upgrading.
Changes made to repo to maintain functionality and make tests pass:
Any instance of the tests calling the `database.db.init_app(current_app)` function was removed because the most recent version of Flask handles app initialisation by itself and doesn't require Werkzeug for that purpose. Hence, this line of code is unnecessary and was causing an error where it was trying to look for a `LocalProxy` Werkzeug object that didn't exist anymore.
The `paginate` method for flask-SQLAlchemy now requires keyword parameters rather than positional parameters, so any instance of this method now has the parameters explicitly defined.
The `get_engine` method for flask-SQLAlchemy doesn't …
> Flask upgrade

- _infra/helm/secure-message/Chart.yaml
- _infra/helm/secure-message/templates/deployment.yaml
This PR adds a wait time for cloud_sql_proxy and stops verbose logging. Currently we deploy the app with a side car cloud_sql_proxy container to access the db. However when a pod is redeployed and the proxy container is sent a SIGTERM the container does not close down gracefully and will kill all connections instantly (i.e sql queries). This naturally gets passed back up the chain to the respondent who will get an error. With us currently using a default pool of 5 and overflow of 10, it means anything up to 15 respondents could get an error when we deploy a new release to prod, which ain't good.
It almost certainly is the reason we see hanging queries and spikes on rollouts in Grafana. This PR adds a term_timeout which will allow the proxy to complete it's query (at least give it 30 …
> RAS-850 Cloud sql proxy term timeout and verbose

- _infra/helm/secure-message/Chart.yaml
- _infra/helm/secure-message/templates/deployment.yaml
- _infra/helm/secure-message/values.yaml
- config.py
Secure messaging should default to INFO and not DEBUG
> Making logging level configurable

- .github/workflows/main.yml
- _infra/helm/secure-message/Chart.yaml
- secure_message/repository/modifier.py
- secure_message/repository/retriever.py
- secure_message/resources/messages.py
- secure_message/resources/threads.py
- tests/app/test_app.py
- tests/app/test_modifier.py
- tests/app/test_retriever.py
- tests/endpoints/test_messages_endpoints.py
- tests/endpoints/test_threads_endpoints.py
Adds error handling around database errors and tests around this. Also updated the GHA workflow with the new `setup-gcloud` and replaces how we create the release
I haven't found a way to test this easily when deployed through spinnaker as other services fall over when there is a database connection issue (I cause this by deleting the postgres configmap). Instead I deploy the secure message PR locally and either insert `raise SQLAlchemyError` where it's being tested or then stop the local postgres deployment
- update uaa client secret so that secure message can connect to uaa on startup
- run local postgres, securemessage, rOps and/or frontstage
- make a SQLAlchemyError happen
- make sure that the whole stack trace is not printed to the logs …
> database error handling

- README.md
- _infra/helm/secure-message/Chart.yaml
Updating references to the now removed `docker-compose` in favour of `docker compose`
No functional changes
[RAS-1238](https://jira.ons.gov.uk/browse/RAS-1238)
> RAS-1238 Update to docker compose from docker-compose

- Makefile
- Pipfile.lock
This PR update flask CORS due to a vulnerability
edit:  on update another issue has been found which there is no fix so has been ignored
CORS is only used in the app create, so the fact the test run says it all. You can however deploy and run the app and acceptance tests if you like (I did)
> RAS-1296 Update Flask cors in secure-message
